// <auto-generated />
namespace BanHangOnline.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class editProductCategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editProductCategory));
        
        string IMigrationMetadata.Id
        {
            get { return "202410220125196_editProductCategory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
